# Generated by Django 3.2.7 on 2021-10-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_alter_feed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='updated_at',
        ),
    ]
