# Generated by Django 3.2.7 on 2021-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_remove_feed_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='title',
        ),
        migrations.AddField(
            model_name='feed',
            name='like',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
