# Generated by Django 3.2.7 on 2021-10-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20211005_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='like',
            field=models.IntegerField(blank=True),
        ),
    ]
