# Generated by Django 3.2.7 on 2021-10-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_alter_feed_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='context',
            new_name='content',
        ),
    ]
